# Generated by Django 2.0.6 on 2018-06-29 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('betHomeScore', models.PositiveIntegerField(blank=True, null=True)),
                ('betGuestScore', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('money', models.FloatField(blank=True, null=True)),
                ('isEdited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36)),
                ('short_name', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('descr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dateStart', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('baseHomeScore', models.PositiveIntegerField(blank=True, null=True)),
                ('baseGuestScore', models.PositiveIntegerField(blank=True, null=True)),
                ('totalHomeScore', models.PositiveIntegerField(blank=True, null=True)),
                ('totalGuestScore', models.PositiveIntegerField(blank=True, null=True)),
                ('koeffHome', models.FloatField(blank=True, null=True)),
                ('koeffDraw', models.FloatField(blank=True, null=True)),
                ('koeffGuest', models.FloatField(blank=True, null=True)),
                ('isOver', models.BooleanField(default=False)),
                ('event_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromMatch', to='fifa2018.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PartyMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NickName', models.CharField(blank=True, max_length=40)),
                ('UsrRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=150)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('groupLetter', models.CharField(blank=True, max_length=1)),
                ('event_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromTeam', to='fifa2018.Event')),
            ],
        ),
        migrations.AddField(
            model_name='partymembers',
            name='Participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromPartyArray', to='fifa2018.Player'),
        ),
        migrations.AddField(
            model_name='partymembers',
            name='partyRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromPartyArray', to='fifa2018.Party'),
        ),
        migrations.AddField(
            model_name='match',
            name='teamGuest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='fifa2018.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='teamHome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='fifa2018.Team'),
        ),
        migrations.AddField(
            model_name='bets',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formBets', to='fifa2018.Match'),
        ),
        migrations.AddField(
            model_name='bets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formBets', to='fifa2018.Player'),
        ),
    ]
